language: java

matrix:
  include:
    - os: osx
      osx_image: xcode9
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: oraclejdk8

sudo: true

install: "./.travis_install.sh"
script: "./.travis_run_tests.sh"

cache:
  directories:
      - $HOME/.m2
